name: Android Build and Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        java-package: jdk
    - name: Clean up
      run: bash ./gradlew clean
    - name: Build with Gradle
      run: bash ./gradlew build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        path: app/build/outputs/apk/
        
        
    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: |
    #       app/build/outputs/apk/debug/app-debug.apk
    #       app/build/outputs/apk/release/app-release-unsigned.apk
