name: Android Build and Release

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        java-package: jdk
    - name: Clean up
      run: bash ./gradlew clean
    - name: Build with Gradle
      run: bash ./gradlew build
